name: Build and package RoBERTa-sequencing to Dockerhub

on:
  # Triggers the workflow on push or pull request events for the main branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Authenticate with Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    - name: set auto-install of extensions
      run: az config set extension.use_dynamic_install=yes_without_prompt

    - name: install az ml
      run: az extension add -n ml -y

    - name: install az extension azure-cli-ml
      run: az extension add -n azure-cli-ml

    - name: attach workspace
      run: az ml folder attach -w "blair-ml" -g "byhillsboro_rg_2380"

    - name: retreive the model
      run: az ml model download -t "." --model-id "roberta-sequence:1"

    - name: build flask-app container
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: false
        tags: blair90/roberta:latest

    - name: Authenticate to Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKER_HUB_USERNAME}}
        password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
